apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-api"
data:
  {{ range $key, $value := .Values.secrets.api }}
    {{ $key | toString | upper }}: {{ $value | toString | b64enc | quote }}
  {{ end }}
type: Opaque
