apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api"
  labels:
    app: "{{ .Release.Name }}-api"
spec:
  ports:
    - protocol: TCP
      port: "{{ .Values.api.port }}"
      targetPort: "{{ .Values.api.port }}"
  selector:
    app: "{{ .Release.Name }}-api"
  type: ClusterIP