apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  DB_HOST: "{{ .Values.db.host }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_NAME: "{{ .Values.db.name }}"
