apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-web"
  labels:
    app: "{{ .Release.Name }}-web"
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.web.port | int  }}
      targetPort: {{ .Values.web.port | int  }}
  selector:
    app: "{{ .Release.Name }}-web"
  type: ClusterIP