@file:OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)

import java.util.Properties
import org.gradle.api.DefaultTask
import org.gradle.api.provider.Property
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

composeCompiler {
    enableIntrinsicRemember = true
}

// ── Read secret from local.properties ──────────────────────────────
val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.inputStream().use { localProperties.load(it) }
}

fun getSecret(key: String, defaultValue: String = ""): String {
    val envKey = key.replace(".", "_").uppercase()
    return System.getenv(envKey)
        ?: project.findProperty(key)?.toString()
        ?: localProperties.getProperty(key, defaultValue)
}

abstract class GenerateAppConfigTask : DefaultTask() {
    @get:Input
    abstract val appsScriptUrlAndroid: Property<String>

    @get:Input
    abstract val appsScriptUrlDesktop: Property<String>

    @get:Input
    abstract val imgbbApiKey: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile
        val configFile = dir.resolve("com/dnd/helper/data/config/GeneratedConfig.kt")
        configFile.parentFile.mkdirs()
        configFile.writeText(
            """
            // AUTO-GENERATED by Gradle task 'generateAppConfig'. DO NOT EDIT.
            package com.dnd.helper.data.config

            object GeneratedConfig {
                const val WEB_APP_URL_ANDROID = "${appsScriptUrlAndroid.get()}"
                const val WEB_APP_URL_DESKTOP = "${appsScriptUrlDesktop.get()}"
                const val IMGBB_API_KEY = "${imgbbApiKey.get()}"
            }
            """.trimIndent()
        )
    }
}

// ── Generate config class from local.properties ────────────────────
val generateAppConfig = tasks.register<GenerateAppConfigTask>("generateAppConfig") {
    appsScriptUrlAndroid.set(getSecret("apps.script.url.android"))
    appsScriptUrlDesktop.set(getSecret("apps.script.url.desktop"))
    imgbbApiKey.set(getSecret("imgbb.api.key"))
    outputDir.set(layout.buildDirectory.dir("generated/source/config"))
}

// Ensure config is generated before any Kotlin compilation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateAppConfig)
}

kotlin {
    androidTarget {
        publishLibraryVariants("release")
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }
    jvm("desktop") {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }
    wasmJs {
        browser {
            commonWebpackConfig {
                devServer?.apply {
                    port = 8080 // You can change this if needed
                }
            }
        }
    }

    sourceSets {
        val commonMain by getting {
            // Include generated config as source
            kotlin.srcDir(generateAppConfig.flatMap { it.outputDir })

            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)
                implementation(compose.components.uiToolingPreview)

                implementation(libs.kotlinx.coroutines.core)
                api(libs.kotlinx.serialization.json)

                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.client.logging)
                implementation(libs.ktor.client.websockets)
                implementation(libs.ktor.serialization.kotlinx.json)

                implementation(libs.koin.core)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)

                implementation(libs.coil.compose)
                implementation(libs.coil.network.ktor3)

                implementation(libs.lifecycle.viewmodel)
                api(project(":models"))
            }
        }

        val androidMain by getting {
            dependencies {
                implementation(libs.koin.android)
                implementation(libs.ktor.client.okhttp)
                implementation(libs.kotlinx.coroutines.android)
            }
        }

        val desktopMain by getting {
            dependencies {
                implementation(libs.ktor.client.java)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.jlayer)
                implementation(libs.poi)
                implementation(libs.poi.ooxml)
            }
        }

        val wasmJsMain by getting {
            dependencies {
                implementation(libs.ktor.client.js)
            }
        }
    }
}

android {
    namespace = "com.dnd.helper.shared.core"
    compileSdk = 36

    defaultConfig {
        minSdk = 29
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        compose = true
    }
}
