import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

composeCompiler {
    enableIntrinsicRemember = true
}

// ── Read secret from local.properties ──────────────────────────────
val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.inputStream().use { localProperties.load(it) }
}
val appsScriptUrl: String = localProperties.getProperty("apps.script.url", "")

// ── Generate config class from local.properties ────────────────────
val generateAppConfig = tasks.register("generateAppConfig") {
    val outputDir = layout.buildDirectory.dir("generated/source/config").get().asFile
    outputs.dir(outputDir)
    doLast {
        val configFile = outputDir.resolve("com/dnd/helper/data/config/GeneratedConfig.kt")
        configFile.parentFile.mkdirs()
        configFile.writeText(
            """
            // AUTO-GENERATED by Gradle task 'generateAppConfig'. DO NOT EDIT.
            package com.dnd.helper.data.config

            object GeneratedConfig {
                const val WEB_APP_URL = "$appsScriptUrl"
            }
            """.trimIndent()
        )
    }
}

// Ensure config is generated before any Kotlin compilation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateAppConfig)
}

kotlin {
    androidTarget {
        publishLibraryVariants("release")
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }
    jvm("desktop")
    wasmJs {
        browser()
    }

    sourceSets {
        val commonMain by getting {
            // Include generated config as source
            kotlin.srcDir(generateAppConfig.map { it.outputs.files.singleFile })

            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)
                implementation(compose.components.uiToolingPreview)

                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)

                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.client.logging)
                implementation(libs.ktor.serialization.kotlinx.json)

                implementation(libs.koin.core)
                implementation(libs.koin.compose)
                implementation(libs.koin.compose.viewmodel)

                implementation(libs.coil.compose)
                implementation(libs.coil.network.ktor3)

                implementation(libs.lifecycle.viewmodel)
                implementation(libs.navigation.compose)
            }
        }

        val androidMain by getting {
            dependencies {
                implementation(libs.androidx.activity.compose)
                implementation(libs.koin.android)
                implementation(libs.ktor.client.okhttp)
                implementation(libs.kotlinx.coroutines.android)
            }
        }

        val desktopMain by getting {
            dependencies {
                implementation(libs.ktor.client.java)
                implementation(libs.kotlinx.coroutines.swing)
            }
        }

        val wasmJsMain by getting {
            dependencies {
                implementation(libs.ktor.client.js)
            }
        }
    }
}

android {
    namespace = "com.dnd.helper.shared"
    compileSdk = 36

    defaultConfig {
        minSdk = 29
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        compose = true
    }
}
