name: Release api

on:
  push:
    branches:
      - 'release/all/v*.*.*'
      - 'release/api/v*.*.*'
    tags:
      - 'release/all/v*.*.*'
      - 'release/api/v*.*.*'

jobs:
  release:
    uses: chmonya-inc/dnd-manager/.github/workflows/docker.yml@v1
    with:
      image-name: chmonya777/dndmanager-api
      dockerfile-path: dockerfiles/api.Dockerfile
      release-name: dndmanager-api
      k8s-namespace: dndmanager
      app-name: api
    secrets: inherit
