name: Release android app

on:
  push:
    branches:
      - release/all**
      - release/app**
    tags:
      - release/all**
      - release/app**

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mv properties/app.properties ./local.properties
      - run: chmod +x gradlew
      - run: ./gradlew :app:assembleDebug
        env:
          APPS_SCRIPT_URL_ANDROID: ${{ secrets.APPS_SCRIPT_URL_ANDROID }}
          APPS_SCRIPT_URL_DESKTOP: ${{ secrets.APPS_SCRIPT_URL_DESKTOP }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: dnd-manager-windows
          path: app/build/outputs/apk/debug/app-debug.apk
