name: Release desktop

on:
  push:
    branches:
      - release/all**
      - release/desktop**
    tags:
      - release/all**
      - release/desktop**

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew :desktop:packageDistributionForCurrentOS
        env:
          APPS_SCRIPT_URL_ANDROID: ${{ secrets.APPS_SCRIPT_URL_ANDROID }}
          APPS_SCRIPT_URL_DESKTOP: ${{ secrets.APPS_SCRIPT_URL_DESKTOP }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: dnd-manager-windows
          path: desktop/build/compose/binaries/main/msi
