name: Build docker image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      use-config-secrets:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
          file: ${{ inputs.dockerfile-path }}
          build-args: |
            ${{ inputs.build-args }}
            ${{ inputs.use-config-secrets && format('APPS_SCRIPT_URL_ANDROID={0}', secrets.APPS_SCRIPT_URL_ANDROID) || '' }}
            ${{ inputs.use-config-secrets && format('APPS_SCRIPT_URL_DESKTOP={0}', secrets.APPS_SCRIPT_URL_DESKTOP) || '' }}
            ${{ inputs.use-config-secrets && format('IMGBB_API_KEY={0}', secrets.IMGBB_API_KEY) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
