name: Release desktop

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
        default: ubuntu
      build-script:
        required: true
        type: string
      build-path:
        required: false
        type: string
      artifact-name:
        required: false
        type: string
        default: "artifact"
      build-envs:
        required: false
        type: string
        default: "{}"
      archive:
        required: false
        type: string
        default: false
    outputs:
      artifact-id:
        description: "ID of the uploaded MSI artifact"
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    name: Run gradle
    runs-on: ${{ inputs.runs-on }}
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полная история для работы git-версионирования

      - name: Validate build-env JSON
        env:
          ENV_JSON: ${{ inputs.build-envs }}
        run: |
          echo "$ENV_JSON" | jq empty || { echo "Invalid JSON"; exit 1; }

      - name: Load build-envs into Environment
        env:
          ENV_JSON: ${{ inputs.build-envs }}
        run: |
          echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: chmod +x gradlew

      - run: ./gradlew ${{ inputs.build-script }} --build-cache
        env:
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}

      - uses: actions/upload-artifact@v7
        if: ${{ inputs.build-path }}
        id: upload-artifact
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.build-path }}
          archive: ${{ inputs.archive }}
          if-no-files-found: error
          retention-days: 3
