name: Bump tag version

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get new app version
      id: new_tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ steps.generate_token.outputs.token }}
        dry_run: true

    - name: Await Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ steps.generate_token.outputs.token }}
        approvers: dnd-manager-developers
        minimum-approvals: 1
        issue-title: "Release ${{ steps.new_tag.outputs.new_tag }}"
        issue-body: "Approve to create new release version ${{ steps.new_tag.outputs.new_tag }}"

    - name: Bump version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ steps.generate_token.outputs.token }}

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        tag_name: ${{ steps.new_tag.outputs.new_tag }}
        release_name: ${{ steps.new_tag.outputs.new_tag }}
        body: ${{ steps.new_tag.outputs.changelog }}
        draft: true
        prerelease: false
