name: Publish app release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      artifact-ids:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v3
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        artifact-ids: ${{ inputs.artifact-ids }}
        path: release
        merge-multiple: true

    - name: Create Draft Release and Upload Assets
      run: |
        gh release create ${{ inputs.tag }} ./release/* --title "DND Manager" --clobber
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
