name: Test build and deploy

on:
  pull_request:
    branches:
      - master


jobs:
  build-api:
    name: Build api
    uses: chmonya-inc/dnd-manager/.github/workflows/docker.yml@v2
    with:
      image-name: chmonya777/dndmanager-api
      image-tag: ${{ github.sha }}
      dockerfile-path: dockerfiles/api.Dockerfile
    secrets: inherit

  build-web:
    name: Build web
    uses: chmonya-inc/dnd-manager/.github/workflows/docker.yml@v2
    with:
      image-name: chmonya777/dndmanager-web
      image-tag: ${{ github.sha }}
      dockerfile-path: dockerfiles/web.Dockerfile
      use-config-secrets: true
    secrets: inherit

  build-desktop:
    name: Build desktop
    permissions:
      contents: write
    uses: chmonya-inc/dnd-manager/.github/workflows/desktop.yml@v2
    with:
      version: ${{ github.sha }}
    secrets: inherit

  build-app:
    name: Build mobile app
    permissions:
      contents: write
    uses: chmonya-inc/dnd-manager/.github/workflows/android.yml@v2
    with:
      version: ${{ github.sha }}
    secrets: inherit

  deploy-api:
    needs: [build-api]
    uses: chmonya-inc/dnd-manager/.github/workflows/deploy.yml@v2
    with:
      version: ${{ github.run_number }}
      image-name: chmonya777/dndmanager-api
      image-tag: ${{ github.sha }}
      release-name: dndmanager-api
      k8s-namespace: dndmanager-test
      app-name: api
      environment: test
    secrets: inherit

  deploy-web:
    needs: [build-web]
    uses: chmonya-inc/dnd-manager/.github/workflows/deploy.yml@v2
    with:
      version: ${{ github.run_number }}
      image-name: chmonya777/dndmanager-web
      image-tag: ${{ github.sha }}
      release-name: dndmanager-web
      k8s-namespace: dndmanager-test
      app-name: web
      environment: test
    secrets: inherit
