name: Release web

on:
  push:
    branches:
      - 'release/all/v*.*.*'
      - 'release/web/v*.*.*'
    tags:
      - 'release/all/v*.*.*'
      - 'release/web/v*.*.*'

jobs:
  release:
    uses: chmonya-inc/dnd-manager/.github/workflows/docker.yml@v1
    with:
      image-name: chmonya777/dndmanager-web
      dockerfile-path: dockerfiles/web.Dockerfile
      release-name: dndmanager-web
      k8s-namespace: dndmanager
      app-name: web
      use-config-secrets: true
    secrets: inherit
