name: DND Manager Web

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  RELEASE_NAME: dndmanager-web
  IMAGE_NAME: chmonya777/dndmanager-web
  K8S_NAMESPACE: dndmanager
  DOCKERFILE: web.Dockerfile

jobs:
  build:
    runs-on: raspberrypi
    steps:
    - uses: actions/checkout@v4
    - name: Login into dockerhub
      run: |
        sudo podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io
    - name: Build image
      run: |
        sudo podman image build -f $DOCKERFILE --cache-from $IMAGE_NAME -t $IMAGE_NAME:$GITHUB_SHA .
    - name: Tag as latest for future builds
      run: |
        sudo podman tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:latest
    - name: Push image
      run: |
        sudo podman push $IMAGE_NAME:$GITHUB_SHA && \
        sudo podman push $IMAGE_NAME:latest
    - name: Delete image locally
      run: |
        sudo podman rmi $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:latest
  deploy:
    needs: build
    runs-on: raspberrypi
    steps:
    - name: Apply deployment
      run: |
        helm secrets upgrade $RELEASE_NAME .helm/templates/web \
          --install \
          --set-string image.name=$IMAGE_NAME \
          --set-string image.tag=$GITHUB_SHA \
          -f .helm/values.yaml \
          -f .helm/.encrypted/secrets.yaml \
          -n $K8S_NAMESPACE
    - name: Wait for deploy
      run: kubectl rollout status deployment $RELEASE_NAME -n $K8S_NAMESPACE --timeout=300s
